server:
  port: 8888
spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: "configserver-repo"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luucaohoanq/springboot-microservice-jwt-auth-config-server
#          username: 'your_github_username'
#          password: 'your_github_token'
          default-label: main
          search-paths: configurations-dev # ref to the directory in the repo
          clone-on-start: true


    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.eclipse.jgit: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh,refresh,health"