spring:
  application:
    name: product-service
  #  profiles:
  #    active: native
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh,health,info"