spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password1231231
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

decorator:
  datasource:
    p6spy:
      enable-logging: true

# Scalar Config
# Ref: https://guides.scalar.com/scalar/scalar-api-references/integrations/spring-boot
scalar:
  enabled: true

  #  https://registry.scalar.com/@scalar/apis/galaxy/latest?format=json
  url: https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.json
  path: /scalar-v2
  theme: moon

app:
  welcome: "Updated Hello !"