api:
  prefix: /api

spring:
  application:
    name: auth-server

  # Database configuration
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:you_username_here@example.com}
    password: ${MAIL_PASSWORD:your_password_here}
    base-url: http://127.0.0.1:${server.port:4005}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}

server:
  port: 4005

# Service URLs (fallback if Eureka is not available)
user-service:
  url: http://localhost:4007

# JWT Configuration
jwt:
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  expiration: 3600 # 1 hour in seconds
  expiration-refresh-token: 86400 # 24 hours in seconds
